name: 'Check conditions'
description: 'Checks provided PR data against configured requirements'
inputs:
  days-to-merge-limit:
    description: 'Upper and lower limit of PR lifetime in days.'
  days-to-merge:
    description: >
      'Number of days from PR opened to merged. Not set if PR not merged.'
  additional-commits-limit:
    description: >
      'Upper and lower limit of commits created after PR opened and before '
      'merged.'
  additional-commits:
    description: 'Count of commits created after PR opened and before merged.'
  code-changed-limit:
    description: >
      'Upper and lower limit of total lines added or deleted in the PR.'
  code-changed:
    description: 'Total lines added or deleted in the PR.'
outputs:
  satisfied:
    description: 'Indicates if all conditions satisfied'
runs:
  using: 'node16'
  main: 'dist/index.js'
