name: 'Check conditions'
description: 'Checks provided PR data against configured requirements'
inputs:
  data:
    description: 'Data relevant to PR'
    required: true
  time-to-merge-condition:
    description: 'Upper and lower limit of PR lifetime in days.'
  duration-in-days:
    description: >
      'Number of days from PR opened to merged. Not set if PR not merged.'
  additional-commits-condition:
    description: >
      'Upper and lower limit of commits created after PR opened and before '
      'merged.'
  additional-commits:
    description: 'Count of commits created after PR opened and before merged.'
outputs:
  satisfied:
    description: 'Indicates if all conditions satisfied'
runs:
  using: 'node16'
  main: 'dist/index.js'
