name: Test create Behavioral Experience

on:
  pull_request:
    types:
      - closed

env:
  COMMENTARY: 'Testing "Behavioral Experience" GitHub action.'

jobs:
  test-behavioral-experience:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v3
      - name: Check-conditions action unit tests
        run: |
          cd .github/actions/check-conditions
          npm ci
          npm test
      - name: Behavioral Experience action end-to-end test
        uses: ./
        with:
          api-token: ${{ secrets.TEST_API_TOKEN }}
          consortium-id: ${{ secrets.TEST_CONSORTIUM_ID }}
          commentary: ${{ env.COMMENTARY }}
          weight: 3
          activity-id: ${{ secrets.TEST_ACTIVITY_ID }}
          category-ids: ${{ secrets.TEST_CATEGORY_IDS }}
          team-ids: ${{ secrets.TEST_TEAM_IDS }}
          PR-time-to-merge-condition: 1,3
          PR-additional-commits-condition: 2,5
          PR-total-changes-condition: 10,
          skip-setup: 'true'
