name: Test check-conditions action code

on: [pull_request, workflow_dispatch]

jobs:
  test-process-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v3
      - name: Check-conditions action unit tests
        run: |
          cd .github/actions/check-conditions
          npm ci
          npm test
